### PR TITLE
Refactoring module

### PR DESCRIPTION
**Pull request by SoulSilence**

### CODE REVIEW

**Comment by steve-todorov** [comment]
Ignore failing CI builds - will be fixed in another PR.

**Comment by steve-todorov** [comment]
Manual tests using docker images:
1. `maven` = successful
2. `gradle-it` = successful
3. `sbt-it` = successful
4. `nuget-it` = successful (more on this in the chat)

@carlspring mentioned that we should rename the directories to omit the `-it` suffix so that `gradle-it` becomes `gradle`, `nuget-it` becomes `nuget` and so on.

**Comment by SoulSilence** [comment]
@steve-todorov 
Hmm. I don't know why, but on my machine at this moment gradle tests fail.

But before open PR I checked and it worked. Looks strange.

UPD: I checked. It is the consequence of shared strongbox for all tests.I remove wrong assertion

**Comment by carlspring** [comment]
Thanks for cleaning this up!

**Pull request merged**
