### PR TITLE
Issue 1827: Update integration tests to use Gradle 6.6.1

### LINKED ISSUE #1827: Upgrade the version of Gradle in strongbox-web-integration to the latest
# Task Description

As part of #1825 , we need to upgrade the version of Gradle in [strongbox-web-integration-tests] to the latest.

# Tasks

The following tasks will need to be carried out:
* [ ] Update [ci-build-images] to use the latest version of Gradle for Linux.
* [ ] Rebuild the images for Gradle.
* [ ] Check if all the tests in the [strongbox-web-integration-tests] still pass.

# Task Relationships

This task:
* Is a sub-task of: #1825

# Useful Links

* [strongbox-web-integration-tests]
* [ci-build-images]

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[ci-build-images]: https://github.com/strongbox/ci-build-images

### PR DESCRIPTION
**Pull request by j4ckofalltrades**
# Pull Request Description

This pull request closes strongbox/strongbox#1827

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [x] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Questions

* Does this pull request break backward compatibility? 
  * [ ] Yes
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No
  
# Code Review And Pre-Merge Checklist

* [ ] My code follows the [coding convention](https://strongbox.github.io/developer-guide/coding-convention.html) of this project.
* [x] I have performed a self-review of my own code.
* [ ] I have commented my code in hard-to-understand areas.
* [ ] My changes generate no new warnings.
* [ ] I have added tests that prove my fix is effective or that my feature works.
* [x] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Review by carlspring — APPROVED** [review]
LGTM, thanks! :)

We do have this image pushed now, right?

**Comment by carlspring** [comment]
To answer my own question, [yes](https://hub.docker.com/layers/strongboxci/alpine/jdk8-mvn3.6-gradle6.6/images/sha256-6b1bb1ba655befb41fc99b4e8fd162bad18ad860a383462c77bcfc08c97efefd?context=explore).

**Comment by steve-todorov** [comment]
LGTM as well, but can you please make sure you have [Allowed changes to PR from maintainers](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) ticked? :)

**Comment by j4ckofalltrades** [comment]
@steve-todorov Yep it is.

pr

**Review by steve-todorov — APPROVED** [review]
LGTM! Thank you very much for your contribution! :)

**Pull request merged**
