### PR TITLE
Issue 1252: New test for raw proxy repository

### LINKED ISSUE #1252: Implement a test that creates a raw proxy repository and attempts to download an artifact through it
# Task Description

We need a new test to be added to the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project that creates a raw proxy repository and resolves an artifact through it.

# Tasks

The following tasks will need to be carried out:
* [ ] Create a new module called `raw` under the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project.
* [ ] Add a new test in the module that creates a `Raw` proxy repository to `https://services.gradle.org/distributions/` and attempts to download `https://services.gradle.org/distributions/gradle-5.3-bin.zip`.

# References

* The [strongbox.yaml](https://strongbox.github.io/user-guide/configuration-files/strongbox-yaml.html)
* Our [REST API](https://strongbox.github.io/user-guide/rest-api.html).
* `org.carlspring.strongbox.client.RestClient` : This class should provide you the means to create a repository over the REST API. It might need to be improved.
* Have a look at the other modules in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) project and try to follow the same approach of doing things.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

### PR DESCRIPTION
**Pull request by bamarch**
"Implement a test that creates a raw proxy
repository and attempts to download an artifact
through it"

- Create a new module 'raw' under the
  strongbox-web-integration-tests project
- Add a new test in the module that:
    * creates a raw proxy repository
    * attempts to download a file from the
      raw proxy repo

closes strongbox/strongbox#1252

### CODE REVIEW

**Comment by bamarch** [comment]
Opening this PR to kick off the Jenkins build, to see if it works 

i.e. are the issues I saw in #1252 locally still present on Jenkins

**Comment by bamarch** [comment]
hmm @carlspring one more thing - I updated the Jenkinsfile with a stage for "raw" but it doesn't look like the tests that run automatically are picking it up. Perhaps it uses the version of the Jenkinsfile in master?

https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox-web-integration-tests/detail/PR-49/3/pipeline

**Comment by carlspring** [comment]
@steve-todorov : Any ideas, regarding the Jenkins issue?

**Comment by steve-todorov** [comment]
Sorry for the delay in replying. I had to figure out a way to make the parallel stages generate dynamically so that we can re-use them in strongbox/strongbox as well. This is working as expected, but please don't merge it right now. I need to do a few more tests related to the pipeline.

P.S. Yes, @bamarch, the build jobs are using the `master` revision of the Jenkinsfile for security reasons and usually require our attention before changes can be applied. :)

**Comment by bamarch** [comment]
Ok sure - @carlspring I can just leave #1252 for now then and move on with another ticket?

**Comment by steve-todorov** [comment]
I've `rebased` this PR and I've also made the necessary changes in the `Jenkinsfile` so that the parallel `s-w-i-t` stages are generated dynamically (SB-1410).

@fuss86 / @carlspring / @sbespalov This PR needs some attention, because we dropped [`maven-commons`](https://github.com/strongbox/strongbox/pull/1324) which is currently used in the [test-raw-proxy-repository.groovy](https://github.com/strongbox/strongbox-web-integration-tests/pull/49/files#diff-bb7482f3fa33ca93078990dbc4876e8eR1). Could you guys check it out and make the necessary changes so we can merge it in the `master`? Thanks in advance!

**Comment by bamarch** [comment]
> I've `rebased` this PR and I've also made the necessary changes in the `Jenkinsfile` so that the parallel `s-w-i-t` stages are generated dynamically (SB-1410).
> 
> @fuss86 / @carlspring / @sbespalov This PR needs some attention, because we dropped [`maven-commons`](https://github.com/strongbox/strongbox/pull/1324) which is currently used in the [test-raw-proxy-repository.groovy](https://github.com/strongbox/strongbox-web-integration-tests/pull/49/files#diff-bb7482f3fa33ca93078990dbc4876e8eR1). Could you guys check it out and make the necessary changes so we can merge it in the `master`? Thanks in advance!

I'm back from my holiday now, I can look at this - I would need to replace the method used for checking the shasums then maven-commons isn't required

**Comment by bamarch** [comment]
OK I removed the dependency, tested with docker-compose and looks good to me.

Not sure about my style choices here though, mixing Java with groovy, happy to re-do anything shouldn't take long right

**Comment by fuss86** [comment]
Hi @bamarch, alternatively you can use `org.carlspring.strongbox.util.MessageDigestUtils#calculateChecksum`

FYI, @steve-todorov

**Comment by bamarch** [comment]
> Hi @bamarch, alternatively you can use `org.carlspring.strongbox.util.MessageDigestUtils#calculateChecksum`
> 
> FYI, @steve-todorov

great thanks, done that now

**Comment by steve-todorov** [comment]
Great! Thanks @bamarch and @fuss86! Merging! :)

**Comment by carlspring** [comment]
Thanks for looking into this for us, @bamarch ! :)

**Pull request merged**
